/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jocopa3.macropad.gui;

import static com.jocopa3.macropad.ActionEnums.*;
import com.jocopa3.macropad.*;

/**
 *
 * @author Matt
 */
public class ActionEditPanel extends javax.swing.JPanel {

    private final ActionEvent event;
    
    /**
     * Creates new form ActionEditPanel
     */
    public ActionEditPanel(ActionEvent event) {
        this.event = event;
        initComponents();
        
        TypeComboBox.setSelectedIndex(ActionType.toInt(event.getType()));
        KeyComboBox.setModel(new javax.swing.DefaultComboBoxModel(ActionEnums.KEYBOARD_KEY_NAMES));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        KeyboardPanel = new javax.swing.JPanel();
        KeyComboBox = new javax.swing.JComboBox();
        KeyLabel = new javax.swing.JLabel();
        KeyStateLabel = new javax.swing.JLabel();
        KeyboardState = new javax.swing.JComboBox();
        DelayPanel = new javax.swing.JPanel();
        DelayLabel = new javax.swing.JLabel();
        DelaySpinner = new javax.swing.JSpinner();
        TypeComboBox = new javax.swing.JComboBox();
        OptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        KeyLabel.setText("Key:");

        KeyStateLabel.setText("State:");

        KeyboardState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pressed", "Released", "Typed" }));

        javax.swing.GroupLayout KeyboardPanelLayout = new javax.swing.GroupLayout(KeyboardPanel);
        KeyboardPanel.setLayout(KeyboardPanelLayout);
        KeyboardPanelLayout.setHorizontalGroup(
            KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeyboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(KeyboardPanelLayout.createSequentialGroup()
                        .addComponent(KeyStateLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KeyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KeyboardState, 0, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        KeyboardPanelLayout.setVerticalGroup(
            KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeyboardPanelLayout.createSequentialGroup()
                .addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeyLabel)
                    .addComponent(KeyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeyStateLabel)
                    .addComponent(KeyboardState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DelayLabel.setText("Delay (milliseconds):");

        DelaySpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout DelayPanelLayout = new javax.swing.GroupLayout(DelayPanel);
        DelayPanel.setLayout(DelayPanelLayout);
        DelayPanelLayout.setHorizontalGroup(
            DelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelayPanelLayout.createSequentialGroup()
                .addComponent(DelayLabel)
                .addGap(18, 18, 18)
                .addComponent(DelaySpinner))
        );
        DelayPanelLayout.setVerticalGroup(
            DelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DelayLabel)
            .addComponent(DelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(ActionType.asStringArray()));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        OptionsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout OptionsPanelLayout = new javax.swing.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        jLabel1.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeComboBox, 0, 270, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(OptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        event.setType(ActionType.fromInt(TypeComboBox.getSelectedIndex()));
        InitializeOptionsPanel();
    }//GEN-LAST:event_TypeComboBoxActionPerformed

    private void AddPanelToOptions(javax.swing.JPanel panel) {
        javax.swing.GroupLayout OptionsPanelLayout = new javax.swing.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsPanelLayout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );
    }
    
    private void InitializeOptionsPanel() {
        OptionsPanel.removeAll();
        switch(event.getType()) {
            case DELAY_EVENT:
                AddPanelToOptions(DelayPanel);
                break;
            case KEYBOARD_EVENT:
                AddPanelToOptions(KeyboardPanel);
                break;
        }
        OptionsPanel.revalidate();
        OptionsPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DelayLabel;
    private javax.swing.JPanel DelayPanel;
    private javax.swing.JSpinner DelaySpinner;
    private javax.swing.JComboBox KeyComboBox;
    private javax.swing.JLabel KeyLabel;
    private javax.swing.JLabel KeyStateLabel;
    private javax.swing.JPanel KeyboardPanel;
    private javax.swing.JComboBox KeyboardState;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JComboBox TypeComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
