/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jocopa3.macropad.gui;

import static java.awt.event.KeyEvent.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.jocopa3.macropad.Action;
import com.jocopa3.macropad.ActionEvent;

/**
 *
 * @author Matt
 */
public class ActionPanel extends javax.swing.JPanel {
    
    private Action action;
    
    /**
     * Creates new form ActionPanel
     */
    public ActionPanel(Action action) {
        this.action = action;
        initComponents();
        initEventsList();
    }
    
    private void initEventsList() {
        EventsList.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return action.size(); }
            
            @Override
            public Object getElementAt(int i) { return action.get(i); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EventsList = new javax.swing.JList();
        AddActionButton = new javax.swing.JButton();
        DeleteActionButton = new javax.swing.JButton();
        EditActionButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ColorPickerButton = new javax.swing.JButton();

        EventsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EventsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EventsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(EventsList);

        AddActionButton.setText("Add Action");
        AddActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionButtonActionPerformed(evt);
            }
        });

        DeleteActionButton.setText("Delete Action");
        DeleteActionButton.setEnabled(false);
        DeleteActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionButtonActionPerformed(evt);
            }
        });

        EditActionButton.setText("Edit Action");
        EditActionButton.setEnabled(false);
        EditActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionButtonActionPerformed(evt);
            }
        });

        ColorPickerButton.setText("Button Color");
        ColorPickerButton.setPreferredSize(new java.awt.Dimension(135, 62));
        ColorPickerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorPickerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(EditActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ColorPickerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddActionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditActionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteActionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColorPickerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionButtonActionPerformed
        ActionEvent newEvent = new ActionEvent(action.getRobot());

        JOptionPane.showMessageDialog(null, new ActionEditPanel(newEvent), "Add Event", JOptionPane.NO_OPTION);
        
        int index = EventsList.getSelectedIndex();
        if(index >= 0)
            action.add(index+1, newEvent);
        else
            action.add(newEvent);
        
        initEventsList();
    }//GEN-LAST:event_AddActionButtonActionPerformed

    private void EditActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionButtonActionPerformed
        int index = EventsList.getSelectedIndex();
        
        if(index >= 0) {
            JOptionPane.showMessageDialog(null, new ActionEditPanel(action.get(index)), "Edit Event", JOptionPane.NO_OPTION);
        }
        
        initEventsList();
    }//GEN-LAST:event_EditActionButtonActionPerformed

    private void DeleteActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionButtonActionPerformed
        int index = EventsList.getSelectedIndex();
        
        if(index >= 0)
            action.remove(index);
        
        initEventsList();
    }//GEN-LAST:event_DeleteActionButtonActionPerformed

    private void EventsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EventsListValueChanged
        boolean enable = EventsList.getSelectedIndex() >= 0; 
        
        EditActionButton.setEnabled(enable);
        DeleteActionButton.setEnabled(enable);
    }//GEN-LAST:event_EventsListValueChanged

    private void ColorPickerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorPickerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorPickerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddActionButton;
    private javax.swing.JButton ColorPickerButton;
    private javax.swing.JButton DeleteActionButton;
    private javax.swing.JButton EditActionButton;
    private javax.swing.JList EventsList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
